version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.13
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error,debug,info},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    networks:
      - default
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  backend:
    build:
      dockerfile: Dockerfile
      context: mse1h2024-clock-ml-backend
    depends_on:
      rabbitmq:
        condition: service_healthy
      ml:
        condition: service_started
    links:
      - ml
      - rabbitmq
    ports:
      - "746:746"
    networks:
      - default
  ml:
    build:
      dockerfile: Dockerfile
      context: mse1h2024-clock-ml-processing
    links:
      - rabbitmq
    ports:
      - "745:745"
    networks:
      - default
  frontend:
    build:
      dockerfile: Dockerfile
      context: mse1h2024-clock-ml-frontend
    ports:
      - "80:80"

networks:
  default:

volumes:
  rabbit_data:
